import 'dart:convert';

List<Database> databaseFromJson(String str) =>
    List<Database>.from(json.decode(str).map((x) => Database.fromJson(x)));

String databaseToJson(List<Database> data) =>
    json.encode(List<dynamic>.from(data.map((x) => x.toJson())));

class Database {
  String nombre;
  String databaseId;
  int id;
  String sexo;
  String fechaDeNacimiento;
  int edad;
  String menorDeEdadAdultoMayor;
  String responsable;
  String correoElectrnico;
  String eps;
  int celular;
  String direccin;
  String vacunaCovid;
  int dosis;
  String patologa;
  String antecedentesMdicos;
  String discapacidad;
  String alrgicoA;
  String observaciones;
  int peso;
  int estaturaCm;
  String intervenciones;

  Database({
    required this.nombre,
    required this.databaseId,
    required this.id,
    required this.sexo,
    required this.fechaDeNacimiento,
    required this.edad,
    required this.menorDeEdadAdultoMayor,
    required this.responsable,
    required this.correoElectrnico,
    required this.eps,
    required this.celular,
    required this.direccin,
    required this.vacunaCovid,
    required this.dosis,
    required this.patologa,
    required this.antecedentesMdicos,
    required this.discapacidad,
    required this.alrgicoA,
    required this.observaciones,
    required this.peso,
    required this.estaturaCm,
    required this.intervenciones,
  });

  factory Database.fromJson(Map<String, dynamic> json) => Database(
        nombre: json["NOMBRE"],
        databaseId: json["ID"],
        id: json["#ID"],
        sexo: json["SEXO"],
        fechaDeNacimiento: json["FECHA DE NACIMIENTO"],
        edad: json["EDAD"],
        menorDeEdadAdultoMayor: json["¿MENOR DE EDAD? ¿ADULTO MAYOR?"],
        responsable: json["RESPONSABLE"],
        correoElectrnico: json["CORREO ELECTRÓNICO"],
        eps: json["EPS"],
        celular: json["CELULAR"],
        direccin: json["DIRECCIÓN"],
        vacunaCovid: json["VACUNA COVID"],
        dosis: json["DOSIS"],
        patologa: json["PATOLOGÍA"],
        antecedentesMdicos: json["ANTECEDENTES MÉDICOS"],
        discapacidad: json["DISCAPACIDAD"],
        alrgicoA: json["ALÉRGICO A"],
        observaciones: json["OBSERVACIONES"],
        peso: json["PESO"],
        estaturaCm: json["ESTATURA (CM)"],
        intervenciones: json["INTERVENCIONES"],
      );

  Map<String, dynamic> toJson() => {
        "NOMBRE": nombre,
        "ID": databaseId,
        "#ID": id,
        "SEXO": sexo,
        "FECHA DE NACIMIENTO": fechaDeNacimiento,
        "EDAD": edad,
        "¿MENOR DE EDAD? ¿ADULTO MAYOR?": menorDeEdadAdultoMayor,
        "RESPONSABLE": responsable,
        "CORREO ELECTRÓNICO": correoElectrnico,
        "EPS": eps,
        "CELULAR": celular,
        "DIRECCIÓN": direccin,
        "VACUNA COVID": vacunaCovid,
        "DOSIS": dosis,
        "PATOLOGÍA": patologa,
        "ANTECEDENTES MÉDICOS": antecedentesMdicos,
        "DISCAPACIDAD": discapacidad,
        "ALÉRGICO A": alrgicoA,
        "OBSERVACIONES": observaciones,
        "PESO": peso,
        "ESTATURA (CM)": estaturaCm,
        "INTERVENCIONES": intervenciones,
      };
}

const String dummyDate = '''
[
 {
  "NOMBRE": "Paciente_1",
  "ID": "CC",
  "#ID": 1,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/01/2003",
  "EDAD": 20,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo1@gmail.com",
  "EPS": "SANITAS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 1",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 3,
  "PATOLOGÍA": "CÁNCER DE MAMA",
  "ANTECEDENTES MÉDICOS": "FRACTURA DE FÉMUR",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 70,
  "ESTATURA (CM)": 172,
  "INTERVENCIONES": "REDUCCIÓN FÉMUR"
 },
 {
  "NOMBRE": "Paciente_2",
  "ID": "CC",
  "#ID": 2,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/02/1998",
  "EDAD": 25,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo2@gmail.com",
  "EPS": "NUEVA EPS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 2",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 3,
  "PATOLOGÍA": "ASMA BRONQUIAL",
  "ANTECEDENTES MÉDICOS": "ASMA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 80,
  "ESTATURA (CM)": 185,
  "INTERVENCIONES": "RINOPLASTIA"
 },
 {
  "NOMBRE": "Paciente_3",
  "ID": "CC",
  "#ID": 3,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/03/1993",
  "EDAD": 30,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo3@gmail.com",
  "EPS": "ASMET SALUD ",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 3",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 3,
  "PATOLOGÍA": "DIABETES MELLITUS",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 100,
  "ESTATURA (CM)": 168,
  "INTERVENCIONES": "BYPASS GÁSTRICO"
 },
 {
  "NOMBRE": "Paciente_4",
  "ID": "CC",
  "#ID": 4,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/04/1988",
  "EDAD": 35,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo4@gmail.com",
  "EPS": "SALUD TOTAL",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 4",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 3,
  "PATOLOGÍA": "HIPERTENSIÓN ARTERIAL",
  "ANTECEDENTES MÉDICOS": "INFARTO DE MIOCARDIO",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 98,
  "ESTATURA (CM)": 182,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_5",
  "ID": "CC",
  "#ID": 5,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/05/1983",
  "EDAD": 40,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo5@gmail.com",
  "EPS": "SANITAS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 5",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 3,
  "PATOLOGÍA": "ARTRITIS REUMATOIDE",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 54,
  "ESTATURA (CM)": 162,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_6",
  "ID": "CC",
  "#ID": 6,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/06/1978",
  "EDAD": 45,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo6@gmail.com",
  "EPS": "NUEVA EPS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 6",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 3,
  "PATOLOGÍA": "PARKINSON",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 60,
  "ESTATURA (CM)": 164,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_7",
  "ID": "CC",
  "#ID": 7,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/07/1973",
  "EDAD": 50,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo7@gmail.com",
  "EPS": "ASMET SALUD ",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 7",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 3,
  "PATOLOGÍA": "ALZHEIMER",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 67,
  "ESTATURA (CM)": 175,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_8",
  "ID": "CC",
  "#ID": 8,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/08/1968",
  "EDAD": 55,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo8@gmail.com",
  "EPS": "SALUD TOTAL",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 8",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 3,
  "PATOLOGÍA": "EPOC",
  "ANTECEDENTES MÉDICOS": "ASMA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 58,
  "ESTATURA (CM)": 160,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_9",
  "ID": "CC",
  "#ID": 9,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/09/1963",
  "EDAD": 60,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "NO APLICA",
  "RESPONSABLE": "NO APLICA",
  "CORREO ELECTRÓNICO": "correo9@gmail.com",
  "EPS": "SANITAS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 9",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 3,
  "PATOLOGÍA": "DEPRESIÓN MAYOR",
  "ANTECEDENTES MÉDICOS": "INTENTO DE SUICIDIO",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 68,
  "ESTATURA (CM)": 164,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_10",
  "ID": "CC",
  "#ID": 10,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/10/1958",
  "EDAD": 65,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 1",
  "CORREO ELECTRÓNICO": "correo10@gmail.com",
  "EPS": "NUEVA EPS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 10",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 3,
  "PATOLOGÍA": "ANEMINA FERROPÉNICA",
  "ANTECEDENTES MÉDICOS": "DESNUTRICIÓN",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 40,
  "ESTATURA (CM)": 170,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_11",
  "ID": "CC",
  "#ID": 11,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/11/1953",
  "EDAD": 70,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 2",
  "CORREO ELECTRÓNICO": "correo11@gmail.com",
  "EPS": "ASMET SALUD ",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 11",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 3,
  "PATOLOGÍA": "SÍNDROME DE INTESTINO IRRITABLE",
  "ANTECEDENTES MÉDICOS": "CÁNCER DE COLON",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 60,
  "ESTATURA (CM)": 180,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_12",
  "ID": "CC",
  "#ID": 12,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/12/1948",
  "EDAD": 75,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 3",
  "CORREO ELECTRÓNICO": "correo12@gmail.com",
  "EPS": "SALUD TOTAL",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 12",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 3,
  "PATOLOGÍA": "ENFERMEDAD DE CROHN",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 65,
  "ESTATURA (CM)": 173,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_13",
  "ID": "CC",
  "#ID": 13,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/13/1943",
  "EDAD": 80,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 4",
  "CORREO ELECTRÓNICO": "correo13@gmail.com",
  "EPS": "SANITAS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 13",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 3,
  "PATOLOGÍA": "LUPUS ERITEMATOSO SISTEMAÁTICO",
  "ANTECEDENTES MÉDICOS": "INSUFICIENCIA HEPÁTICA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 49,
  "ESTATURA (CM)": 155,
  "INTERVENCIONES": "DRENAJE ARTICULAR "
 },
 {
  "NOMBRE": "Paciente_14",
  "ID": "CC",
  "#ID": 14,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/14/1938",
  "EDAD": 85,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 5",
  "CORREO ELECTRÓNICO": "correo14@gmail.com",
  "EPS": "NUEVA EPS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 14",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 3,
  "PATOLOGÍA": "ESQUIZOFRENIA",
  "ANTECEDENTES MÉDICOS": "TUMOR CEREBRAL",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 73,
  "ESTATURA (CM)": 183,
  "INTERVENCIONES": "RESECCIÓN TUMORAL"
 },
 {
  "NOMBRE": "Paciente_15",
  "ID": "CC",
  "#ID": 15,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/15/1933",
  "EDAD": 90,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "ADULTO MAYOR",
  "RESPONSABLE": "ACUDIENTE 6",
  "CORREO ELECTRÓNICO": "correo15@gmail.com",
  "EPS": "ASMET SALUD ",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 15",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 3,
  "PATOLOGÍA": "MIGRAÑA SEVERA",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 72,
  "ESTATURA (CM)": 176,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_16",
  "ID": "TI",
  "#ID": 16,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/16/2022",
  "EDAD": 1,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "MENOR DE EDAD",
  "RESPONSABLE": "ACUDIENTE 7",
  "CORREO ELECTRÓNICO": "correo16@gmail.com",
  "EPS": "SALUD TOTAL",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 16",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 1,
  "PATOLOGÍA": "HIPOTIROIDISMO",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 10,
  "ESTATURA (CM)": 70,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_17",
  "ID": "TI",
  "#ID": 17,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/17/2021",
  "EDAD": 2,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "MENOR DE EDAD",
  "RESPONSABLE": "ACUDIENTE 8",
  "CORREO ELECTRÓNICO": "correo17@gmail.com",
  "EPS": "SANITAS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 17",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 1,
  "PATOLOGÍA": "HIPERTIROIDISMO",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "NO",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 13,
  "ESTATURA (CM)": 86,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_18",
  "ID": "TI",
  "#ID": 18,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/18/2020",
  "EDAD": 3,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "MENOR DE EDAD",
  "RESPONSABLE": "ACUDIENTE 9",
  "CORREO ELECTRÓNICO": "correo18@gmail.com",
  "EPS": "NUEVA EPS",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 18",
  "VACUNA COVID": "PFIZER",
  "DOSIS": 1,
  "PATOLOGÍA": "FIBROMIALGIA",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 15,
  "ESTATURA (CM)": 94,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_19",
  "ID": "TI",
  "#ID": 19,
  "SEXO": "M",
  "FECHA DE NACIMIENTO": "01/19/2019",
  "EDAD": 4,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "MENOR DE EDAD",
  "RESPONSABLE": "ACUDIENTE 10",
  "CORREO ELECTRÓNICO": "correo19@gmail.com",
  "EPS": "ASMET SALUD ",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 19",
  "VACUNA COVID": "MODERNA",
  "DOSIS": 1,
  "PATOLOGÍA": "INSUFICIENCIA RENAL CRÓNICA",
  "ANTECEDENTES MÉDICOS": "CÁNCER DE RIÑÓN",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 19,
  "ESTATURA (CM)": 103,
  "INTERVENCIONES": "NO REGISTRA"
 },
 {
  "NOMBRE": "Paciente_20",
  "ID": "TI",
  "#ID": 20,
  "SEXO": "F",
  "FECHA DE NACIMIENTO": "01/20/2018",
  "EDAD": 5,
  "¿MENOR DE EDAD? ¿ADULTO MAYOR?": "MENOR DE EDAD",
  "RESPONSABLE": "ACUDIENTE 11",
  "CORREO ELECTRÓNICO": "correo20@gmail.com",
  "EPS": "SALUD TOTAL",
  "CELULAR": 1234567890,
  "DIRECCIÓN": "DIRECCIÓN 20",
  "VACUNA COVID": "SINOVAC ",
  "DOSIS": 1,
  "PATOLOGÍA": "ESCLEROSIS MÚLTIPLE",
  "ANTECEDENTES MÉDICOS": "NO REGISTRA",
  "DISCAPACIDAD": "SI",
  "ALÉRGICO A": "NO REGISTRA",
  "OBSERVACIONES": "NO REGISTRA",
  "PESO": 16,
  "ESTATURA (CM)": 109,
  "INTERVENCIONES": "NO REGISTRA"
 }
]
''';
