name: mary
description: Bienvenido a nuestra aplicación de cuidados de la salud. Aquí encontrarás todas las herramientas y recursos que necesitas para mejorar y mantener tu bienestar físico y mental.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  go_router: ^6.5.9
  google_fonts: ^4.0.4
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
