// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMylrVnogza691LhUBoRsGvmwkWUsoMY',
    appId: '1:574727339286:web:bd85d719000fc8c8b42437',
    messagingSenderId: '574727339286',
    projectId: 'mary-health-app',
    authDomain: 'mary-health-app.firebaseapp.com',
    storageBucket: 'mary-health-app.appspot.com',
    measurementId: 'G-982MSMZ4EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB13uXLkW52DKnCZiRhZJ_5O9L7nKpmYU8',
    appId: '1:574727339286:android:20d6a4a54e088555b42437',
    messagingSenderId: '574727339286',
    projectId: 'mary-health-app',
    storageBucket: 'mary-health-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9IjSTpatfDtDS9YO-STN69e6kLyQ8RM',
    appId: '1:574727339286:ios:6a241fd12ccf0d69b42437',
    messagingSenderId: '574727339286',
    projectId: 'mary-health-app',
    storageBucket: 'mary-health-app.appspot.com',
    iosClientId:
        '574727339286-qou24c2f8dg55rm6mi4o5aj6k571jl9m.apps.googleusercontent.com',
    iosBundleId: 'com.phollux.org.mary',
  );
}
