// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDLVc3E_FVu539g7-_wUU3kZZU-C9HDEs',
    appId: '1:5928709485:web:ca67d7e329365489ea7e64',
    messagingSenderId: '5928709485',
    projectId: 'mary-health-app-stg',
    authDomain: 'mary-health-app-stg.firebaseapp.com',
    storageBucket: 'mary-health-app-stg.appspot.com',
    measurementId: 'G-PVQ13WV5QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FNJKWDH4c3m_ee5ZBjlOGPOhUbENIXY',
    appId: '1:5928709485:android:b41ad913dfde003aea7e64',
    messagingSenderId: '5928709485',
    projectId: 'mary-health-app-stg',
    storageBucket: 'mary-health-app-stg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNbSMpaRvv-oi1pQvrGRuU1K-sWcfZb6c',
    appId: '1:5928709485:ios:fada70abd9c7fc2dea7e64',
    messagingSenderId: '5928709485',
    projectId: 'mary-health-app-stg',
    storageBucket: 'mary-health-app-stg.appspot.com',
    iosClientId:
        '5928709485-gk2p4atqv1f7949jgt14tsp1v3ed9n53.apps.googleusercontent.com',
    iosBundleId: 'com.phollux.org.mary.stg',
  );
}
